id: IFCFA4B07
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T03:51:25+00:00'
last_modified: '2022-06-08T02:16:11.866860+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25903
  title: དབྱི་སོའི་གཏམ་རྒྱུད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    008F:
      image_group_id: I1KG25905
      title: ''
      total_pages: 263
      order: 1
      base_file: 008F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
