id: P004606
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25903
  title: དབྱི་སོའི་གཏམ་རྒྱུད།
  author: ''
  volumes:
    414bbf933f3d4c3cba7223a5c51b1120:
      image_group_id: I1KG25905
      title: ''
      volume_number: 1
      total_pages: 263
